#ifndef FULLY_HOMOMORPHIC_ENCRYPTION_TRANSPILER_EXAMPLES_DISCREET_LOGS_DISCREET_LOGS_READ_ALL_H
#define FULLY_HOMOMORPHIC_ENCRYPTION_TRANSPILER_EXAMPLES_DISCREET_LOGS_DISCREET_LOGS_READ_ALL_H

const int READ_ALL_MAX = 2;
const int READ_ALL_COUNT = 2;

void readAll(
  char record[READ_ALL_MAX+1], 
  int counter[1+1],
  char result[READ_ALL_MAX*READ_ALL_COUNT+1]
);

#endif  // FULLY_HOMOMORPHIC_ENCRYPTION_TRANSPILER_EXAMPLES_DISCREET_LOGS_DISCREET_LOGS_READ_ALL_H




