#ifndef FULLY_HOMOMORPHIC_ENCRYPTION_TRANSPILER_EXAMPLES_DISCREET_LOGS_DISCREET_LOGS_SELECT_INDEX_H
#define FULLY_HOMOMORPHIC_ENCRYPTION_TRANSPILER_EXAMPLES_DISCREET_LOGS_DISCREET_LOGS_SELECT_INDEX_H

const unsigned short MAX_ARRAY_SIZE = 4;

void selectIndex(
  char db[MAX_ARRAY_SIZE], 
  short db_idx[MAX_ARRAY_SIZE], 
  char query[MAX_ARRAY_SIZE], 
  short query_params[2], 
  short result[1]
);

#endif  // FULLY_HOMOMORPHIC_ENCRYPTION_TRANSPILER_EXAMPLES_DISCREET_LOGS_DISCREET_LOGS_SELECT_INDEX_H
